### ISSUE TITLE
setup Lambda infrastructure in AWS for Meetup.com

### ISSUE THREAD

**Issue by thescientist13** [ProvidenceGeeks/website-lambda-meetup#3]
## Type of Change
- [ ] New Feature Request
- [ ] Improvement / Suggestion
- [ ] Bug
- [x] Other (please clarify below)

## Summary

This is a technical task to get the needed resources in AWS provisioned and documented in the README
1.  S3 Bucket
1.  Lambda (NodeJS)
1.  Cron

**Comment by thescientist13** [comment]
Bucket made and data uploading, as part of #5 / #9 
https://s3.amazonaws.com/providencegeeks.com/external-services-data/meetup/meetup-data.json

**Comment by thescientist13** [comment]
@mdiwale 
Please confirm you can open that file above

**Comment by mdiwale** [comment]
@thescientist13 
Yes I could open the file.

**Comment by thescientist13** [comment]
<img width="681" alt="screen shot 2017-10-27 at 9 55 47 am" src="https://user-images.githubusercontent.com/895923/32127413-a5855212-bb44-11e7-94b5-cbd183ece0f5.png">
